apiVersion: apps/v1
kind: ReplicaSet
metadata:
# pod의 이름은 네임스페이스 내에서 유일해야함
  name: nginx-replicaset
  namespace: youngkwan
spec:
  replicas: 2
  # 아래의 label은 replicaset이 관리해야 할 파드를 결정하는 데 사용
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
    # 아래의 labels는 service의 selector.app과 일치해야함
      labels:
        app: my-nginx
    spec: 
      containers:
      - name: my-nginx
        image: nginx
        ports: 
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: youngkwan
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx